# NAME: Mudassar Hanif
PIAIC Batch 4 Roll Number: PIAIC76574 TIME: 11:15 T0 1:15 QUARTER: 2 COURSE: AI ASSIGNMENT: 1 NUMPY SESSION: 2

In [1]:
import numpy as np

In [2]:
np.__version__

'1.19.4'

In [3]:
nlist = np.arange(1,10,2,dtype=int) #1 numpy range
nlist

array([1, 3, 5, 7, 9])

In [4]:
nlist.shape # or np.shape(nlist)

(5,)

In [5]:
nlist.dtype

dtype('int32')

In [6]:
arr2d = np.array([[3,4,5,7], [4,4,5,2]]) #2convert the pure python list into numpy array

In [7]:
arr2d.ndim

2

In [8]:
arr2d.shape

(2, 4)

In [9]:
arr2d.dtype

dtype('int32')

In [10]:
zarr = np.zeros((3,3), dtype=float, order='C')  #3 generate an array with all 0 entries
zarr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
zarr = np.zeros((3,3), dtype=int, order='F')
zarr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [12]:
np.zeros_like(arr2d)  #4 Return an array of zeros with the same shape and type as a given array.

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [13]:
np.empty((4,2), dtype=int)  #5 Return a new array of given shape and type, without initializing entries.

array([[1, 0],
       [1, 0],
       [0, 0],
       [0, 0]])

In [14]:
np.empty_like(arr2d)   #6 Return a new array with the same shape and type as a given array.

array([[1, 0, 1, 0],
       [0, 0, 0, 0]])

In [15]:
np.asarray([(1,2), (4,5)])   #7 Convert input to ndarray, but do not copy if the input is already an ndarray.
                #includes lists, lists of tuples, tuples, tuples of tuples, tuplesof lists and ndarrays.

array([[1, 2],
       [4, 5]])

In [16]:
np.ones((1,4,2), dtype=int)    #8 Produce an array of all 1s with the given shape and dtype

array([[[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]]])

In [17]:
np.ones_like(arr2d)   #9 this method takes another array to make its all entries equal 1.

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [18]:
np.full((2,3), fill_value=6)    #10 Produce an array of all 1s with the given shape and dtype "fill value"

array([[6, 6, 6],
       [6, 6, 6]])

In [19]:
np.full_like(arr2d, fill_value=2) #11 it takes another array to act like a full method

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [20]:
np.eye(4,3)   #12 Return a 2-D array with ones on the diagonal and zeros elsewhere

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [21]:
np.eye(4,3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.identity(2, dtype=int)   #13 returns an identity array

array([[1, 0],
       [0, 1]])

In [23]:
print(arr2d.shape, end='\n\n')

print(arr2d)

(2, 4)

[[3 4 5 7]
 [4 4 5 2]]


In [24]:
arr2d.reshape((2,2,2))    #14 Returns an array containing the same data with a new shape.

array([[[3, 4],
        [5, 7]],

       [[4, 4],
        [5, 2]]])

In [25]:
vector = np.arange(8).reshape(2,4)
vector

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [26]:
vector = np.where(vector//2 == 0, 1,-1)   #15 returns a boolean array
vector

array([[ 1,  1, -1, -1],
       [-1, -1, -1, -1]])

In [27]:
np.abs(vector)    #16 Compute the absolute value element-wise for integer, floating-point, or complex values

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [28]:
np.fabs(vector)    #17

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [29]:
sqrt = np.ndarray((3,3)) #18 returns n dimentional numpy array
sqrt

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.sqrt(sqrt)   #19 Return the non-negative square-root of an array, element-wise.

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
np.square(sqrt) # 20 Compute the square of each element (equivalent to arr ** 2)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
np.exp([2,3]) #21 Compute the exponent ex of each element

array([ 7.3890561 , 20.08553692])

In [33]:
np.log([10]) #22 returns log base e

array([2.30258509])

In [34]:
np.log10([10]) # 23 returns log base 10

array([1.])

In [35]:
np.log2([10])  #24 returns log base 2

array([3.32192809])

In [36]:
np.log1p([10]) #25 returns log base (1+x)

array([2.39789527])

In [37]:
np.sign([3,-4,-234, 5]) #26 Compute the sign of each element: 1 (positive), 0 (zero), or –1 (negative)

array([ 1, -1, -1,  1])

In [38]:
np.ceil([2.4, 4.7])  #27 Compute the ceiling of each element (i.e., the smallest integer greater than or equal to that number)

array([3., 5.])

In [39]:
np.floor([2.4, 4.7])  #28  Compute the floor of each element (i.e., the largest integer less than or equal to each element)

array([2., 4.])

In [40]:
np.rint([2.4, 4.7])  #29 Round elements to the nearest integer, preserving the dtype

array([2., 5.])

In [41]:
lst = np.array([2.4, 4.7])

In [42]:
np.modf(lst)  #30 Return fractional and integral parts of array as a separate array

(array([0.4, 0.7]), array([2., 4.]))

In [43]:
np.isnan(lst)  #31 Return boolean array indicating whether each value is NaN (Not a Number)

array([False, False])

In [44]:
inf = np.array([22/7, 5])

In [45]:
np.isinf(inf)  #32 Return boolean array indicating whether each element infinite

array([False, False])

In [46]:
np.isfinite(inf)  #33 Return boolean array indicating whether each element is finite

array([ True,  True])

In [47]:
pi = 22/7
trig = np.array([pi/6, pi/3, pi/2])

In [48]:
np.sin(trig)  #34 trignometric sine, element-wise

array([0.5001825 , 0.86623608, 0.9999998 ])

In [49]:
np.cos(trig)  #35 trignometric cosine, element-wise

array([ 8.65920010e-01,  4.99634929e-01, -6.32244592e-04])

In [50]:
np.tan(trig)  #36 trignometric tangent, element-wise

array([ 5.77631301e-01,  1.73373803e+00, -1.58166604e+03])

In [51]:
np.arcsin(np.array([0.5001825 , 0.86623608, 0.9999998 ]))  #37 Inverse sine, element-wise.

array([0.52380952, 1.04761906, 1.57016387])

In [52]:
np.arccos([0.5001825 , 0.86623608, 0.9999998 ])  #38 inverse cosine;

array([1.04698681e+00, 5.23177269e-01, 6.32455543e-04])

In [53]:
np.arctan([0.5001825 , 0.86623608, 0.9999998 ])  #39 trignometric cotangent function, element-wise

array([0.4637936 , 0.71384475, 0.78539806])

In [54]:
np.sinh(trig)   #40 sine hyperbolic

array([0.54809379, 1.25004168, 2.30288578])

In [55]:
np.cosh(trig)  #41 cos hyperbolic

array([1.14035381, 1.6008136 , 2.51063396])

In [56]:
np.tanh(trig)  #42 tan hyperbolic

array([0.48063486, 0.78087897, 0.9172527 ])

##### Binary universal functions

In [57]:
a = np.arange(1,20, 2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [58]:
b = np.arange(0,20, 2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [59]:
np.add(a,b)  #43 Add corresponding elements in arrays

array([ 1,  5,  9, 13, 17, 21, 25, 29, 33, 37])

In [60]:
np.multiply(a, b)  #44 multiply corresponding elements in arrays

array([  0,   6,  20,  42,  72, 110, 156, 210, 272, 342])

In [61]:
np.divide(a, b)   #45 divide corresponding elements in arrays

C:\Users\Mudassar Hanif\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.5       , 1.25      , 1.16666667, 1.125     ,
       1.1       , 1.08333333, 1.07142857, 1.0625    , 1.05555556])

In [62]:
np.subtract(a, b)  #46 subtract corresponding elements in arrays

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [63]:
np.floor_divide(a,b)  #47 divide element-wise(truncation the remainder)

C:\Users\Mudassar Hanif\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


array([0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [67]:
np.power(b,a)  #48  Raise elements in first array to powers indicated in second array

array([         0,          8,       1024,     279936,  134217728,
       1215752192, 1275068416, -769949696,          0, -355991552],
      dtype=int32)

In [69]:
np.maximum(a, b)  #49  Element-wise maximum

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
np.minimum(a, b)   #50  Element-wise minimum